name: dcrl
channels:
  - conda-forge
dependencies:
  - python=3.12.3
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - networkx
  - pyyaml
  - pytest
  - joblib
  - filelock
  - pydot
  - graphviz
  - tqdm
  - pip
  - pip:
      - factor_analyzer
      - causal-learn
