project_name: Discrete Causal Representation Learning
random_seed: 2026

paths:
  raw_data: data/raw
  processed_data: data/processed
  results: results

experiment:
  name: placeholder_experiment
  save_results: true
